### ISSUE TITLE
[yara] Fail if sample file is missing 

### ISSUE THREAD

**Issue by SnakeByteIL** [botherder/viper#228]
in https://github.com/botherder/viper/blob/master/modules/yarascan.py#L118 

If the sample file is missing it will return None and will break the execution: 
$viper > yara scan
[!] The command yara raised an exception:
Traceback (most recent call last):
  File "/viper/viper/core/ui/console.py", line 257, in start
    module.run()
  File "/viper/modules/yarascan.py", line 191, in run
    self.scan()
  File "/viper/modules/yarascan.py", line 118, in scan
    for match in rules.match(entry_path):
TypeError: argument 1 must be string, not None

**Comment by botherder** [comment]
Closed with 1b6a185.

**Comment by SnakeByteIL** [comment]
Thanks
