### ISSUE TITLE
The command open raised an exception:

### ISSUE THREAD

**Issue by grannymalware** [botherder/viper#232]
misc viper > open -l 1
[!] The command open raised an exception:
Traceback (most recent call last):
  File "/home/viper/viper/viper/core/ui/console.py", line 249, in start
    self.cmd.commands[root]['obj'](*args)
  File "/home/viper/viper/viper/core/ui/commands.py", line 132, in cmd_open
    __sessions__.new(get_sample_path(item.sha256))
  File "/home/viper/viper/viper/core/session.py", line 48, in new
    session.file = File(path)
  File "/home/viper/viper/viper/common/objects.py", line 42, in __init__
    if self.is_valid():
  File "/home/viper/viper/viper/common/objects.py", line 55, in is_valid
    return os.path.exists(self.path) and os.path.isfile(self.path)# and os.path.getsize(self.path) != 0
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

**Comment by lksnyder0** [comment]
I had this same issue and it turned out to be a permission problem. I was running my web ui as root but trying to use the cli as my user. Just drop your web UI to the same user you use the cli with. Next run the follow command in the viper directory
```
chown -R <user>:<user group> * 
```

**Comment by grannymalware** [comment]
Most excellent, thank you.  Worked like a charm!
