### ISSUE TITLE
[API] 

### ISSUE THREAD

**Issue by deralexxx** [botherder/viper#238]
If you change the param from sha256 to sha25 it is breaking the api, but it should be more flexible.

Actually I would expect it to be catched in the code already::
    for entry in ['md5', 'sha256', 'ssdeep', 'tag', 'name', 'all','latest']:
    value = request.forms.get(entry)
    if value:
    key = entry
    break
    if not value:
    response.code = 400
    raise jsonize({'message':'Invalid search term'})

Can someone confirm it?

curl -F sha25=9ce49435b67d531bbd966186920c90ecf0752e88b79af246886b077c8ec9b649 -X POST 127.0.0.1:8080/file/find

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://127.0.0.1:8080/file/find&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
        </body>
    </html>

**Comment by deralexxx** [comment]
This is the command line output:

127.0.0.1 - - [14/Mar/2015 19:28:17] "POST /file/find HTTP/1.1" 200 2
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "api.py", line 159, in find_file
    raise jsonize({'message':'Invalid search term'})
TypeError: exceptions must be old-style classes or derived from BaseException, not str

**Comment by deralexxx** [comment]
ok @botherder merged it
