### ISSUE TITLE
Mach0 module throws exception on file magic

### ISSUE THREAD

**Issue by botherder** [botherder/viper#242]
This exception is raised consistently:
```
viper flashback.bin > macho -a
[!] The command macho raised an exception:
Traceback (most recent call last):
  File "/home/nex/projects/viper/viper/viper/core/ui/console.py", line 257, in start
    module.run()
  File "/home/nex/projects/viper/viper/modules/macho.py", line 84, in run
    m = MachO(__sessions__.current.file.path)
  File "/home/nex/projects/viper/viper/modules/pymacho/MachO.py", line 54, in __init__
    self.load_file(macho_file)
  File "/home/nex/projects/viper/viper/modules/pymacho/MachO.py", line 57, in load_file
    self.header = MachOHeader(macho_file)
  File "/home/nex/projects/viper/viper/modules/pymacho/MachOHeader.py", line 39, in __init__
    self.parse(macho_file)
  File "/home/nex/projects/viper/viper/modules/pymacho/MachOHeader.py", line 47, in parse
    assert self.magic in [MH_MAGIC, MH_CIGAM, MH_MAGIC_64, MH_CIGAM_64]
AssertionError
```
@deralexxx any ideas?

**Comment by deralexxx** [comment]
ok looks like I have to make more exception handling stuff, with the samples I tested it with it worked...

**Comment by botherder** [comment]
Resolved, although I think there should be more testing with file samples pymacho has issues with.
