### ISSUE TITLE
File still exist after deleting

### ISSUE THREAD

**Issue by nyx0** [botherder/viper#248]
I raised this error by deleting an entry that contains a note and tags:
```
> delete
Are you sure you want to delete this binary? Can't be reverted! [y/n] y
[!] The file has notes that will be deleted as well
[!] Node: readme
[!] Unable to delete file

> open -l 1
[!] The command open raised an exception:
Traceback (most recent call last):
  File "/Users/toto/Documents/viper/viper/core/ui/console.py", line 249, in start
    self.cmd.commands[root]['obj'](*args)
  File "/Users/toto/Documents/viper/viper/core/ui/commands.py", line 157, in cmd_open
    __sessions__.new(get_sample_path(item.sha256))
  File "/Users/toto/Documents/viper/viper/core/session.py", line 48, in new
    session.file = File(path)
  File "/Users/toto/Documents/viper/viper/common/objects.py", line 42, in __init__
    if self.is_valid():
  File "/Users/toto/Documents/viper/viper/common/objects.py", line 55, in is_valid
    return os.path.exists(self.path) and os.path.isfile(self.path)# and os.path.getsize(self.path) != 0
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by deralexxx** [comment]
ACK, will push a fix in a minute

**Comment by botherder** [comment]
I should have fixed the problem with the appropriate technique provided by SQLAlchemy. Now the file delete works and notes are deleted as well.
